apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pk29xxbmu-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/pk29xxbmu-java-quarkus-gitops